import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Top.module.css'

import Link from 'next/link'



const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <div className={styles.title}>
          <h1>Comitto or BANNN!!</h1>

          <p className={styles.login}>
            ログイン
          </p>
        </div>
      </header>

      <main className={styles.main}>
        <div className={styles.explosion}>
          <figure className={styles.explosion}>
            <Image src='/explosion.png' alt='explosion' width={1200} height={600} />
          </figure>
          <div className={styles.dead}>
            <h2>生きるか<br />死ぬかは<br />あなた次第</h2>
          </div>
        </div>
        <div className={styles.tutorial} >
          <h2>Comitto or BANNNとは</h2>
          <p>テキストテキストテキストテキスト</p>
        </div>

        <Link href='/new_todo'>
          <a>新規TODO</a>
        </Link>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div >
  )
}

export default Home
