import { style } from '@mui/system'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Top.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.topContainer}>
      <Head>
        <title>COMMITorBAN</title>
        <meta name='description' content='Generated by create next app' />
        <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet" />
      </Head>
      <header className={styles.header}>
        <div className={styles.title}>
          <h1 className={styles.headerLogo}>COMMIT or BAN!!</h1>
          <a className={styles.login}>
            ログイン
          </a>
        </div>
      </header>
      <div className={styles.explosion}>
        <figure className={styles.explosion}>
          <Image src='/explosion.png' alt='explosion' width={1200} height={600} />
        </figure>
        <div className={styles.dead}>
          <h2>追い込みたい<br />そんなあなたに<br />目標管理システム</h2>
        </div>
      </div>
      <div className={styles.tutorial} >
          <div className={styles.inner} >
          <div className={styles.tutorial__ttlEn}>WHAT IS<br className={styles.pcHidden}/> "COMMIT OR BAN?"</div>
          {/* <h2 className={styles.tutorial__ttlJa}>"COMMIT or BAN!!"とは</h2> */}
          <p>"COMMIT or BAN!!"とは皆さんが抱いている理想や目標の達成を、全力で応援するシステムです！<br/>
          <br/>メインキャラクターの”ポセどん”があなたを見守ります。<br/>
          ポセどんはとっってもストイック。<br/>
          そんなポセどんと一緒に頑張っていきましょう！</p>
        </div>
      </div>
      <main>
        <div className={styles.topFlow}>
          <div className={styles.inner}>
          <div className={styles.topFlow__ttlEn}>FLOW</div>
          <h2 className={styles.topFlow__ttlJa}>使い方</h2>
            <div className={styles.topFlowItems}>
            <li className={styles.topFlowItem}>
                <div className={styles.topFlowItem__head}>
                  <div className={styles.topFlowItem__num}>01</div>
                  <div className={styles.topFlowItem__ttl}>目標設定をしよう！</div>
                </div>
              </li>
              <li className={styles.topFlowItem}>
                <div className={styles.topFlowItem__head}>
                  <div className={styles.topFlowItem__num}>02</div>
                  <div className={styles.topFlowItem__ttl}>あなたのこんなことやあんなことを教えてね。</div>
                </div>
                <div className={styles.topFlowItem__imgWrapper}>
                  <figure className={styles.topFlowItem__img}><Image src='/flow01.png' alt='恥ずかしいポセさん01' width={300} height={250} /></figure>
                  <figure className={styles.topFlowItem__img}><Image src='/flow02.JPG' alt='恥ずかしいポセさん02' width={300} height={250} /></figure>
                </div>
              </li>
              <li className={styles.topFlowItem}>
                <div className={styles.topFlowItem__head}>
                  <div className={styles.topFlowItem__num}>03</div>
                  <div className={styles.topFlowItem__ttl}>なんとしてでも目標を達成しよう！<br/>さもなければ、、、</div>
                </div>
                  <figure className={styles.topFlowItem03__img}>
                    <Image src='/tes2.png' alt='Vercel Logo' width={100} height={200} />
                    <figcaption>BANNNNN</figcaption>
                  </figure>
              </li>
            </div>
            <span className={styles.topFlow__txt}><span>ポセどんは怠けものが大嫌い！</span><br/>期限が守れなかったあなたはポセどんのお仕置きをくらうよ！</span>
            </div>
          </div>
          {/* <div className={styles.topAchive}>
            <div className={styles.inner}>
            <p className={styles.topAchive__ttl}>目標達成すると</p>
            <div className={styles.topAchiveContents}>
              <figure className={styles.topAchiveContents__img}><Image src='/tes1.png' alt='Vercel Logo' width={600} height={450} /></figure>
            <p className={styles.topAchiveContents__txt}>ストイックなあなたに癒しの写真をプレゼント</p> 
            </div>
            </div>
          </div> */}
          <div className={styles.topBegin}>
            <div className={styles.inner}>
              <div className={styles.topBegin__lead}>
                さあ、はじめよう！<br/>
                あなたの目標達成を全力で応援します！
              </div>
              <figure className={styles.topBegin__img}>
                <Image src='/sayhi.png' alt='ポセさん' width={150} height={280} />
              </figure>
              <div className={styles.topBtn}>
                <span className={styles.topBtn__link}>ログインする</span>
              </div>
            </div>
        </div>
      </main>
      {/* <main className={styles.main}>
        <Link href='/new_todo'>
          <a>新規TODO</a>
        </Link>
      </main> */}
      <footer className={styles.footer}>

      </footer>
    </div >
  )
}

export default Home
