import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/List.module.css'
import Link from 'next/link'
import { useState } from 'react'
import { Todo, getTodo, editTodo } from '../lib/todo'

const List: NextPage = () => {
  const [todos, setTodos] = useState<Todo[]>([])

  getTodo()
    .then((values) => setTodos(values))
    .catch((err) => console.error(err))

  // 達成
  const [done, setDone] = useState(false)

  // 表示用todoデータ
  const [showDone, setShowDone] = useState(true)
  const showData = showDone ? todos.filter((todo) => !todo.done) : todos.filter((todo) => todo.done)

  // 達成切り替え関数
  function changeDone(event: React.MouseEvent<HTMLLIElement, MouseEvent> | undefined) {
    if (!(event?.target instanceof HTMLLIElement)) {
      return
    }
    if (event.target.className !== 'active') {
      setDone(!done)
      setShowDone(!showDone)
    }
  }

  // todoのループ
  const rows = showData.map((d, index) => (
    <li className={styles.row} key={`todo${index}`}>
      <input
        className={styles.checkbox}
        type='checkbox'
        defaultChecked={done}
        disabled={done}
        onClick={() => editTodo(d.id)}
      />
      <div className={styles.limit}>
        {d.limit.toLocaleDateString()} {d.limit.toLocaleTimeString()}
      </div>
      <div className={styles.todo}>{d.title}</div>
    </li>
  ))
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.tab}>
          <div className={styles.tabHeader}>
            <ul>
              <li className={!done ? styles.active : ''} onClick={changeDone}>
                未達成
              </li>
              <li className={done ? styles.active : ''} onClick={changeDone}>
                達成
              </li>
            </ul>
          </div>
          <div className={styles.tabBody}>
            <ul>{rows}</ul>
          </div>
        </div>

        <div className={styles.buttonWrap}>
          <Link href='/form_todo'>
            <a>目標設定へ</a>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default List
