/* eslint-disable*/
import Link from 'next/link'
import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Modal from './modal'
import { Todo, getTodo, editTodo } from '../lib/todo'
import styles from '../styles/List.module.css'

const List: NextPage = () => {
  const [todos, setTodos] = useState<Todo[]>([])

  getTodo()
    .then((values) => setTodos(values))
    .catch((err) => console.error(err))

  // 達成
  const [done, setDone] = useState(false)

  // 表示用todoデータ
  const [showDone, setShowDone] = useState(true)
  const showData = showDone ? todos.filter((todo) => !todo.done) : todos.filter((todo) => todo.done)

  // 達成切り替え関数
  function changeDone(event: React.MouseEvent<HTMLLIElement, MouseEvent> | undefined) {
    if (!(event?.target instanceof HTMLLIElement)) {
      return
    }
    if (event.target.className !== 'active') {
      setShowDone(!showDone)
      setDone(!done)
    }
  }

  // modal
  const [showModal, setShowModal] = useState(false)

  // doneクリック関数
  function clickDone(d: Todo) {
    setShowModal(true)
    editTodo(d.id)
  }

  function closeShowModal() {
    setShowModal(false)
  }

  // todoのループ
  const rows = showData.map((d, index) => (
    <li className={styles.row} key={`todo${index}`}>
      <div>
        {d.limit.toLocaleDateString()} {d.limit.toLocaleTimeString()}
      </div>
      <div className={styles.todo}>{d.title}</div>
      {!done && (
        <div className={styles.doneBtn} onClick={() => clickDone(d)}>
          done
        </div>
      )}
    </li>
  ))

  // 期限切れのtodoの数をcount
  function countNotDone() {
    const showTodos = showData
    const now = new Date()
    if (!done) {
      // 日付の比較
      const result = showTodos.filter((t) => {
        return t.limit < now
      })
      return result
    }
  }

  // 期限切れがあった時に変更&post
  function commitBan() {
    const countNotDones = countNotDone()
    if (countNotDones) {
      countNotDones.forEach((todo: Todo) => {
        // twitterにpost

        // doneの変更
        editTodo(todo.id)
      })
    }
  }
  commitBan()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.tab}>
          <div className={styles.tabHeader}>
            <ul>
              <li className={!done ? styles.active : ''} onClick={changeDone}>
                未達成
              </li>
              <li className={done ? styles.active : ''} onClick={changeDone}>
                達成
              </li>
            </ul>
          </div>
          <div className={styles.tabBody}>
            <ul>{rows}</ul>
          </div>
        </div>

        <div className={styles.buttonWrap}>
          <Link href='/form_todo'>
            <a>目標設定へ</a>
          </Link>
        </div>
        <Modal showFlag={showModal} closeModal={closeShowModal} />
      </main>
    </div>
  )
}

export default List
/* eslint-disable*/
