import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/List.module.css'
import Link from 'next/link'
import React, { useState } from 'react';


// leaf start code
import { createRoot } from 'react-dom/client'
import { style } from '@mui/system'
const List: NextPage = () => {
  // TODO: todoのローカルストレージをedit
  // TODO: checkを入れたら未達成→達成

  // todo一覧のデータ
  const data:{done:boolean,limit:string,todo:string}[] = [{done:true,limit:'2022-09-24',todo:"-10KG"},{done:false,limit:'2022-09-25',todo:"タスク１を終わらせる"},{done:false,limit:'2022-09-26',todo:"タスク2を終わらせる"}]

  // 達成
  const [done, setDone] = useState(false);
  
  // 表示用todoデータ
  const [showDone, setShowDone] = useState(true);
  const showData = showDone ? data.filter(data =>data.done) : data.filter(data =>!data.done)

  // 達成切り替え関数
  function changeDone(event: React.MouseEvent<HTMLLIElement, MouseEvent> | undefined) {
    if (!(event?.target instanceof HTMLLIElement)) {
    return;
  }
    if (event.target.className !== 'active') {
      setDone(!done);
      setShowDone(!showDone);
    }
  }

  // TODO:この辺でif文使ってdoneがfalseだったらdisabled=false。
  // function changeDisabled(event: React.MouseEvent<HTMLLIElement, MouseEvent> | undefined) {
  //   if (!(event?.target instanceof HTMLLIElement)) {
  //   return;
  // }
  //   if (event.target.className !== 'active') {
  //     setDone(!done);
  //     setShowDone(!showDone);
  //   }
  // }
  // todoのループ
  const rows = showData.map((d, index) =>
    <li className={styles.row}>
      <input className={styles.checkbox} type="checkbox" checked={done}/>
      <div className={ styles.limit } key={`todo${index}`}>{d.limit}</div>
      <div className={ styles.todo} key={`todo${index}`}>{d.todo}</div>
    </li>
  )
  
  // leaf code start
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        
        <div className={styles.tab}>
          <div className={styles.tabHeader}>
            <ul>
              <li className={!done ? styles.active : ''}  onClick={changeDone}>未達成</li>
              <li className={done ? styles.active : '' } onClick={changeDone}>達成</li>
            </ul>
          </div>
          <div className={styles.tabBody}>
            {/* leaf start code  */}
            <ul>
              {/* <input className={styles.checkbox} type="button" /> */}
              {rows}
            </ul>
          </div>
        </div>

        <div className={styles.buttonWrap}>
          {/* ここにボタンを記述 （suzuki） */}
          <Link href='/new_todo'>
            <a>目標設定へ</a>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default List